services:
  shopping-api:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .prod.env
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PWD}@db:5432/ecommerce
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PWD}
      POSTGRES_DB: ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
